=== skullim/beetry/schemas/valid-tree.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "ValidTreeStore",
  "type": "object",
  "properties": {
    "channel": {
      "$ref": "#/$defs/Store4"
    },
    "node": {
      "$ref": "#/$defs/Store"
    },
    "parameter": {
      "$ref": "#/$defs/Store3"
    },
    "port": {
      "$ref": "#/$defs/Store2"
    }
  },
  "required": [
    "node",
    "port",
    "parameter",
    "channel"
  ],
  "$defs": {
    "ChannelConfig": {
      "type": "object",
      "properties": {
        "capacity": {
          "type": "integer",
          "format": "uint",
          "minimum": 0
        },
        "count": {
          "$ref": "#/$defs/SenderReceiverCount"
        },
        "kind": {
          "$ref": "#/$defs/ChannelKind"
        }
      },
      "required": [
        "capacity",
        "count",
        "kind"
      ]
    },
    "ChannelData": {
      "type": "object",
      "properties": {
        "config": {
          "$ref": "#/$defs/ChannelConfig"
        },
        "spec_id": {
          "type": "integer",
          "format": "uint16",
          "maximum": 65535,
          "minimum": 0
        }
      },
      "required": [
        "spec_id",
        "config"
      ]
    },
    "ChannelKind": {
      "oneOf": [
        {
          "type": "object",
          "properties": {
            "Tokio": {
              "$ref": "#/$defs/TokioChannelKind"
            }
          },
          "additionalProperties": false,
          "required": [
            "Tokio"
          ]
        }
      ]
    },
    "ChannelSpec": {
      "type": "object",
      "properties": {
        "msg_hash": {
          "$ref": "#/$defs/MessageHash"
        },
        "msg_type_name": {
          "type": "string"
        }
      },
      "required": [
        "msg_hash",
        "msg_type_name"
      ]
    },
    "DataStore": {
      "type": "object",
      "properties": {
        "store": {
          "type": "object",
          "additionalProperties": false,
          "patternProperties": {
            "^\\d+$": {
              "$ref": "#/$defs/ChannelData"
            }
          }
        }
      },
      "required": [
        "store"
      ]
    },
    "LeafKind": {
      "type": "string",
      "enum": [
        "Action",
        "Condition"
      ]
    },
    "MessageHash": {
      "description": "Describes the hash of the message type (and not concrete message type\ninstance).",
      "type": "object",
      "properties": {
        "hash": {
          "type": "integer",
          "format": "uint64",
          "minimum": 0
        }
      },
      "required": [
        "hash"
      ]
    },
    "NodeKind": {
      "oneOf": [
        {
          "type": "string",
          "enum": [
            "Control",
            "Decorator",
            "Root"
          ]
        },
        {
          "type": "object",
          "properties": {
            "Leaf": {
              "$ref": "#/$defs/LeafKind"
            }
          },
          "additionalProperties": false,
          "required": [
            "Leaf"
          ]
        }
      ]
    },
    "NodeName": {
      "type": "string"
    },
    "NodeSpecKey": {
      "type": "object",
      "properties": {
        "kind": {
          "$ref": "#/$defs/NodeKind"
        },
        "name": {
          "$ref": "#/$defs/NodeName"
        }
      },
      "required": [
        "name",
        "kind"
      ]
    },
    "ParameterValue": {
      "oneOf": [
        {
          "type": "object",
          "properties": {
            "Bool": {
              "type": "boolean"
            }
          },
          "additionalProperties": false,
          "required": [
            "Bool"
          ]
        },
        {
          "type": "object",
          "properties": {
            "U16": {
              "type": "integer",
              "format": "uint16",
              "maximum": 65535,
              "minimum": 0
            }
          },
          "additionalProperties": false,
          "required": [
            "U16"
          ]
        },
        {
          "type": "object",
          "properties": {
            "U64": {
              "type": "integer",
              "format": "uint64",
              "minimum": 0
            }
          },
          "additionalProperties": false,
          "required": [
            "U64"
          ]
        },
        {
          "type": "object",
          "properties": {
            "I64": {
              "type": "integer",
              "format": "int64"
            }
          },
          "additionalProperties": false,
          "required": [
            "I64"
          ]
        },
        {
          "type": "object",
          "properties": {
            "F64": {
              "type": "number",
              "format": "double"
            }
          },
          "additionalProperties": false,
          "required": [
            "F64"
          ]
        },
        {
          "type": "object",
          "properties": {
            "String": {
              "type": "string"
            }
          },
          "additionalProperties": false,
          "required": [
            "String"
          ]
        }
      ]
    },
    "Parameters": {
      "type": "object",
      "properties": {
        "map": {
          "type": "object",
          "additionalProperties": {
            "$ref": "#/$defs/ParameterValue"
          }
        }
      },
      "required": [
        "map"
      ]
    },
    "PortConnectionId": {
      "type": "object",
      "properties": {
        "channel_id": {
          "type": "integer",
          "format": "uint16",
          "maximum": 65535,
          "minimum": 0
        },
        "node_id": {
          "type": "integer",
          "format": "uint16",
          "maximum": 65535,
          "minimum": 0
        },
        "port_id": {
          "type": "integer",
          "format": "uint8",
          "maximum": 255,
          "minimum": 0
        }
      },
      "required": [
        "node_id",
        "port_id",
        "channel_id"
      ]
    },
    "PortSource": {
      "type": "string",
      "enum": [
        "Internal",
        "External"
      ]
    },
    "PortState": {
      "type": "object",
      "properties": {
        "source": {
          "$ref": "#/$defs/PortSource"
        }
      },
      "required": [
        "source"
      ]
    },
    "RecordStore": {
      "type": "object",
      "properties": {
        "store": {
          "type": "object",
          "additionalProperties": false,
          "patternProperties": {
            "^\\d+$": {
              "$ref": "#/$defs/RecordValue"
            }
          }
        }
      },
      "required": [
        "store"
      ]
    },
    "RecordValue": {
      "type": "object",
      "properties": {
        "children": {
          "type": "array",
          "items": {
            "type": "integer",
            "format": "uint16",
            "maximum": 65535,
            "minimum": 0
          }
        },
        "spec_id": {
          "type": "integer",
          "format": "uint16",
          "maximum": 65535,
          "minimum": 0
        }
      },
      "required": [
        "spec_id",
        "children"
      ]
    },
    "SenderReceiverCount": {
      "description": "Represents the current state of connected senders and receivers\nOn channel creation there are no senders and receivers",
      "type": "object",
      "properties": {
        "receiver": {
          "type": "integer",
          "format": "uint",
          "minimum": 0
        },
        "sender": {
          "type": "integer",
          "format": "uint",
          "minimum": 0
        }
      },
      "required": [
        "sender",
        "receiver"
      ]
    },
    "SpecStore": {
      "type": "object",
      "properties": {
        "store": {
          "type": "object",
          "additionalProperties": false,
          "patternProperties": {
            "^\\d+$": {
              "$ref": "#/$defs/NodeSpecKey"
            }
          }
        }
      },
      "required": [
        "store"
      ]
    },
    "SpecStore2": {
      "type": "object",
      "properties": {
        "store": {
          "type": "object",
          "additionalProperties": false,
          "patternProperties": {
            "^\\d+$": {
              "$ref": "#/$defs/ChannelSpec"
            }
          }
        }
      },
      "required": [
        "store"
      ]
    },
    "Store": {
      "type": "object",
      "properties": {
        "nodes": {
          "$ref": "#/$defs/RecordStore"
        },
        "specs": {
          "$ref": "#/$defs/SpecStore"
        }
      },
      "required": [
        "specs",
        "nodes"
      ]
    },
    "Store2": {
      "type": "object",
      "properties": {
        "connections": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/PortConnectionId"
          },
          "uniqueItems": true
        },
        "states": {
          "type": "object",
          "additionalProperties": false,
          "patternProperties": {
            "^\\d+$": {
              "type": "object",
              "additionalProperties": false,
              "patternProperties": {
                "^\\d+$": {
                  "$ref": "#/$defs/PortState"
                }
              }
            }
          }
        }
      },
      "required": [
        "states",
        "connections"
      ]
    },
    "Store3": {
      "type": "object",
      "properties": {
        "parameters": {
          "type": "object",
          "additionalProperties": false,
          "patternProperties": {
            "^\\d+$": {
              "$ref": "#/$defs/Values"
            }
          }
        }
      },
      "required": [
        "parameters"
      ]
    },
    "Store4": {
      "type": "object",
      "properties": {
        "channels": {
          "$ref": "#/$defs/DataStore"
        },
        "specs": {
          "$ref": "#/$defs/SpecStore2"
        }
      },
      "required": [
        "specs",
        "channels"
      ]
    },
    "TokioChannelKind": {
      "type": "string",
      "enum": [
        "Mpsc",
        "Broadcast",
        "Watch"
      ]
    },
    "Values": {
      "type": "object",
      "properties": {
        "params": {
          "$ref": "#/$defs/Parameters"
        }
      },
      "required": [
        "params"
      ]
    }
  }
}

=== skullim/beetry/beetry-example/src/domain/ui/ui_multi_ports.json
{
    "node": {
        "specs": {
            "store": {
                "0": {
                    "name": "Root",
                    "kind": "Root"
                },
                "1": {
                    "name": "Multi Port Publisher",
                    "kind": {
                        "Leaf": "Action"
                    }
                },
                "2": {
                    "name": "Multi Port Subscriber",
                    "kind": {
                        "Leaf": "Action"
                    }
                },
                "3": {
                    "name": "Sequence",
                    "kind": "Control"
                }
            }
        },
        "nodes": {
            "store": {
                "0": {
                    "spec_id": 0,
                    "children": [
                        5
                    ]
                },
                "2": {
                    "spec_id": 2,
                    "children": []
                },
                "3": {
                    "spec_id": 1,
                    "children": []
                },
                "4": {
                    "spec_id": 2,
                    "children": []
                },
                "5": {
                    "spec_id": 3,
                    "children": [
                        3,
                        2,
                        4
                    ]
                }
            }
        }
    },
    "port": {
        "states": {
            "0": {},
            "3": {
                "4": {
                    "source": "Internal"
                },
                "1": {
                    "source": "Internal"
                },
                "3": {
                    "source": "Internal"
                },
                "0": {
                    "source": "Internal"
                },
                "2": {
                    "source": "Internal"
                }
            },
            "5": {},
            "2": {
                "0": {
                    "source": "Internal"
                },
                "4": {
                    "source": "Internal"
                },
                "2": {
                    "source": "Internal"
                },
                "3": {
                    "source": "Internal"
                },
                "1": {
                    "source": "Internal"
                }
            },
            "4": {
                "1": {
                    "source": "Internal"
                },
                "2": {
                    "source": "Internal"
                },
                "3": {
                    "source": "Internal"
                },
                "4": {
                    "source": "Internal"
                },
                "0": {
                    "source": "Internal"
                }
            }
        },
        "connections": [
            {
                "node_id": 3,
                "port_id": 2,
                "channel_id": 6
            },
            {
                "node_id": 3,
                "port_id": 3,
                "channel_id": 9
            },
            {
                "node_id": 4,
                "port_id": 3,
                "channel_id": 9
            },
            {
                "node_id": 3,
                "port_id": 1,
                "channel_id": 5
            },
            {
                "node_id": 3,
                "port_id": 4,
                "channel_id": 7
            },
            {
                "node_id": 2,
                "port_id": 4,
                "channel_id": 7
            },
            {
                "node_id": 4,
                "port_id": 2,
                "channel_id": 6
            },
            {
                "node_id": 4,
                "port_id": 1,
                "channel_id": 5
            },
            {
                "node_id": 2,
                "port_id": 1,
                "channel_id": 5
            },
            {
                "node_id": 2,
                "port_id": 3,
                "channel_id": 9
            },
            {
                "node_id": 4,
                "port_id": 4,
                "channel_id": 7
            },
            {
                "node_id": 3,
                "port_id": 0,
                "channel_id": 8
            },
            {
                "node_id": 4,
                "port_id": 0,
                "channel_id": 8
            },
            {
                "node_id": 2,
                "port_id": 0,
                "channel_id": 8
            },
            {
                "node_id": 2,
                "port_id": 2,
                "channel_id": 6
            }
        ]
    },
    "parameter": {
        "parameters": {}
    },
    "channel": {
        "specs": {
            "store": {
                "0": {
                    "msg_hash": {
                        "hash": 14936812682624361455
                    },
                    "msg_type_name": "PoseA"
                },
                "1": {
                    "msg_hash": {
                        "hash": 12383689559197385902
                    },
                    "msg_type_name": "PoseB"
                },
                "2": {
                    "msg_hash": {
                        "hash": 14115698820061440997
                    },
                    "msg_type_name": "PoseC"
                },
                "3": {
                    "msg_hash": {
                        "hash": 762712500057230228
                    },
                    "msg_type_name": "PoseD"
                },
                "4": {
                    "msg_hash": {
                        "hash": 2514599907018732515
                    },
                    "msg_type_name": "PoseE"
                }
            }
        },
        "channels": {
            "store": {
                "5": {
                    "spec_id": 1,
                    "config": {
                        "capacity": 1,
                        "count": {
                            "sender": 1,
                            "receiver": 2
                        },
                        "kind": {
                            "Tokio": "Broadcast"
                        }
                    }
                },
                "6": {
                    "spec_id": 2,
                    "config": {
                        "capacity": 1,
                        "count": {
                            "sender": 1,
                            "receiver": 2
                        },
                        "kind": {
                            "Tokio": "Broadcast"
                        }
                    }
                },
                "7": {
                    "spec_id": 4,
                    "config": {
                        "capacity": 1,
                        "count": {
                            "sender": 1,
                            "receiver": 2
                        },
                        "kind": {
                            "Tokio": "Broadcast"
                        }
                    }
                },
                "8": {
                    "spec_id": 0,
                    "config": {
                        "capacity": 1,
                        "count": {
                            "sender": 1,
                            "receiver": 2
                        },
                        "kind": {
                            "Tokio": "Broadcast"
                        }
                    }
                },
                "9": {
                    "spec_id": 3,
                    "config": {
                        "capacity": 1,
                        "count": {
                            "sender": 1,
                            "receiver": 2
                        },
                        "kind": {
                            "Tokio": "Broadcast"
                        }
                    }
                }
            }
        }
    }
}

=== skullim/beetry/beetry-example/src/domain/ui/tree.json
{
    "node": {
        "specs": {
            "store": {
                "0": {
                    "name": "Root",
                    "kind": "Root"
                },
                "1": {
                    "name": "Multi Port Publisher",
                    "kind": {
                        "Leaf": "Action"
                    }
                },
                "2": {
                    "name": "Multi Port Subscriber",
                    "kind": {
                        "Leaf": "Action"
                    }
                },
                "3": {
                    "name": "Sequence",
                    "kind": "Control"
                }
            }
        },
        "nodes": {
            "store": {
                "0": {
                    "spec_id": 0,
                    "children": [
                        3
                    ]
                },
                "1": {
                    "spec_id": 1,
                    "children": []
                },
                "2": {
                    "spec_id": 2,
                    "children": []
                },
                "3": {
                    "spec_id": 3,
                    "children": [
                        1,
                        2
                    ]
                }
            }
        }
    },
    "port": {
        "states": {
            "3": {},
            "2": {
                "3": {
                    "source": "Internal"
                },
                "4": {
                    "source": "Internal"
                },
                "0": {
                    "source": "Internal"
                },
                "1": {
                    "source": "Internal"
                },
                "2": {
                    "source": "Internal"
                }
            },
            "1": {
                "1": {
                    "source": "Internal"
                },
                "2": {
                    "source": "Internal"
                },
                "3": {
                    "source": "Internal"
                },
                "4": {
                    "source": "Internal"
                },
                "0": {
                    "source": "Internal"
                }
            },
            "0": {}
        },
        "connections": [
            {
                "node_id": 2,
                "port_id": 1,
                "channel_id": 0
            },
            {
                "node_id": 1,
                "port_id": 4,
                "channel_id": 1
            },
            {
                "node_id": 1,
                "port_id": 0,
                "channel_id": 0
            },
            {
                "node_id": 2,
                "port_id": 3,
                "channel_id": 1
            },
            {
                "node_id": 1,
                "port_id": 2,
                "channel_id": 1
            },
            {
                "node_id": 2,
                "port_id": 0,
                "channel_id": 0
            },
            {
                "node_id": 1,
                "port_id": 1,
                "channel_id": 0
            },
            {
                "node_id": 2,
                "port_id": 2,
                "channel_id": 1
            },
            {
                "node_id": 1,
                "port_id": 3,
                "channel_id": 1
            },
            {
                "node_id": 2,
                "port_id": 4,
                "channel_id": 1
            }
        ]
    },
    "parameter": {
        "parameters": {}
    },
    "channel": {
        "specs": {
            "store": {
                "0": {
                    "msg_hash": {
                        "hash": 13315934175031694117
                    },
                    "msg_type_name": "Pose"
                }
            }
        },
        "channels": {
            "store": {
                "0": {
                    "spec_id": 0,
                    "config": {
                        "capacity": 1,
                        "count": {
                            "sender": 2,
                            "receiver": 2
                        },
                        "kind": {
                            "Tokio": "Broadcast"
                        }
                    }
                },
                "1": {
                    "spec_id": 0,
                    "config": {
                        "capacity": 1,
                        "count": {
                            "sender": 3,
                            "receiver": 3
                        },
                        "kind": {
                            "Tokio": "Broadcast"
                        }
                    }
                }
            }
        }
    }
}
